---
sidebar: sidebar
permalink: use/capacity-review-status.html
keywords: economic efficiency remediate, economic efficiency, capacity planning
summary: If your clusters are currently below or forecasted to be below the threshold of 70% capacity, the economic efficiency service identifies those as low-capacity resources and alerts you.
---

= Review capacity planning status
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
If your clusters are currently below or forecasted to be below the threshold of 70% capacity, the economic efficiency service identifies those as low-capacity resources and alerts you. Additionally, the economic efficiency service provides recommendations on whether you should tier data or obtain additional capacity. 

You can review the following types of data to assist in the capacity issue resolution. 

* Platform
* Country where asset is located 
* Current and forecasted capacity by month
* Capacity utilization and percent 
* Latency trends
* IOPS trends

.Steps 

. From the BlueXP left navigation, select *Governance* > *Economic efficiency* > *Capacity planning*. 
. Select *Evaluate Storage Options* for the asset.
. Choose one of the options: 
+
* *Add Capacity*: Continue by link:../use/capacity-add.html[Adding capacity].
* *Tier cold data*: Continue by link:../use/capacity-tier-data.html[Tiering cold data to cloud storage and free up storage].
* *No action needed*: Continue by link:../use/capacity-reminders.html[Selecting no action and setting reminders to check again].



