---
sidebar: sidebar
permalink: use/capacity-tier-data.html
keywords: economic efficiency remediate, economic efficiency, capacity planning, add capacity
summary: The Economic efficiency service provides recommendations based on forecasted data growth. You can accept the forecast or enter your own forecast. Based on this, the service presents recommendations that satisfy the projected capacity growth and are most optimal for the asset configuration. One of the recommendations might be to tier cold data to cloud storage to free up capacity. This recommendation initiates the connection to NetApp Cloud Tiering, another BlueXP service.  
---

= Tier cold data to cloud storage and free up storage
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
The Economic efficiency service provides recommendations based on forecasted data growth. You can accept the forecast or enter your own forecast. Based on this, the service presents recommendations that satisfy the projected capacity growth and are most optimal for the asset configuration. One of the recommendations might be to tier cold data to cloud storage to free up capacity. This recommendation initiates the connection to NetApp Cloud Tiering, another BlueXP service. 

From there, you can tier the data and easily return to the Economic efficiency service to take action on other systems.  

The cloud tiering process includes these processes: 

* Deploy a Connector 
* Discover the cluster
* Set up tiering to the cloud


.Steps 

. From the BlueXP left navigation, select *Governance* > *Economic efficiency* > *Capacity planning*. 
. Select *Evaluate Storage Options* for the asset.
. Select *Tier Cold Data*.


. The next steps depend on whether you have a BlueXP Connector deployed already and the cluster discovered: 
+
* If you need to deploy the BlueXP Connector, refer to the BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[How to create a connector]. Otherwise, if you already deployed the Connector, the option to deploy the connector does not appear.  
* If the service needs to discover the cluster, refer to https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters]. Otherwise, if the cluster has already been discovered, the option to discover the cluster does not appear. 

+
The Economic efficiency service initiates the connection to the Cloud Tiering service, another NetApp BlueXP service.

. Select *Add Connector*.

. Choose a cloud provider, and select *Continue*. 


. Select *Continue* or *Skip to Deployment*. 
+
After deploying a Connector, BlueXP Cloud Tiering next discovers the cluster, if not already discovered.

. After the cluster is discovered, set up the tiering.
+
For details about tiering, refer to https://docs.netapp.com/us-en/cloud-manager-tiering/index.html[Cloud Tiering service documentation^].

