---
sidebar: sidebar
permalink: get-started/prerequisites.html
keywords: what are bluexp economic efficiency requirements, economic efficiency prerequisites
summary: Get started with BlueXP economic efficiency by verifying support for your environment, network access, login and web browser.
---

= BlueXP economic efficiency prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Get started by verifying the readiness of your operational environment, login, network access, and web browser.

To use Blue economic efficiency, you should ensure that your environment meets all requirements. 

* Your environment must meet all BlueXP requirements including a login and network access from a web browser. 
+
Refer to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html[BlueXP Quick start^] and https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html[BlueXP networking information^].

* You need to have access credentials to the clusters. 

* While not a requirement, it is helpful if the BlueXP Connector is in place and enabled and the ONTAP system is discovered. If not, the service walks you through those processes. 

* If you plan on tiering cold data to cloud storage, ensure that the cluster is eligible per the license. 



