---
sidebar: sidebar
permalink: get-started/prerequisites.html
keywords: what are bluexp economic efficiency requirements, economic efficiency prerequisites
summary: Get started with the BlueXP Economic efficiency by verifying support for your environment, network access, login and web browser.
---

= Economic efficiency prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Get started by verifying the readiness of your operational environment, login, network access, and web browser.

To use the Economic efficiency service, you should ensure that your environment meets all requirements. 

* Your environment must meet all BlueXP requirements including a login and network access from a web browser. 
+
Refer to the BlueXP https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[Getting started checklist].

* You need to have access credentials to the clusters. 

* While not a requirement, it is helpful if the BlueXP Connector is in place and enabled and the ONTAP system is discovered. If not, the service walks you through those processes. 

* If you plan on tiering cold data to cloud storage, ensure that the cluster is eligible per the license. 



