---
sidebar: sidebar
permalink: release-notes/whats-new.html
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions
summary: BlueXP economic efficiency identifies assets with current or forecasted low capacity and provides recommendations on data tiering or additional capacity (for AFF systems).
---

= What's new
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Learn what’s new in BlueXP economic efficiency.

//tag::whats-new[]

== January 2024 
This release of BlueXP economic efficiency enables you to run a workload simulation of your environment on different hardware to evaluate a technology refresh impact. You can add a workload and exclude existing workloads from the simulation. 

Previously, you could only take an assessment of your assets and identify whether a technology refresh is recommended. 

The feature is now part of the Tech refresh option in the left navigation. 

== 08 November 2023 
This release of BlueXP economic efficiency includes a new option to take an assessment of your assets and identify whether a technology refresh is recommended. The service includes a new Tech refresh option in the left navigation, new pages where you can take an assessment of your current workloads and assets, and a report that provides recommendations to you. 

== 02 April 2023 

The new BlueXP economic efficiency service identifies storage assets with current or forecasted low capacity and provides recommendations on data tiering or additional capacity for on-premises AFF systems.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html[Learn more about BlueXP economic efficiency]. 
//include 3 most recent releases
//end::whats-new[]